### ISSUE TITLE
Responsiveness.

### ISSUE THREAD

**Issue by inseldesign** [Viewdesic/viewScroller.js#2]
Hey,

thanks for this nice ViewScroller Script. Do you have any recommendations how to deal with smaller viewports? Thanks in advance for answering. 

Sascha

**Comment by Viewdesic** [comment]
Hi Sascha,
you can manage of width and height of the viewport using for example: <iframe> object (look at the jsfiddle example: [https://jsfiddle.net/Viewdesic/50s38drr/](https://jsfiddle.net/Viewdesic/50s38drr/))
or width only like on examples: [http://www.viewdesic.com/viewscroller/examples/panel-right-fixed.html](http://www.viewdesic.com/viewscroller/examples/panel-right-fixed.html) or [http://www.viewdesic.com/viewscroller/examples/panel-left-fixed.html](http://www.viewdesic.com/viewscroller/examples/panel-left-fixed.html)
Best regards.

**Comment by inseldesign** [comment]
OK thanks. That was clear to me, but what if content is longer than the container which is obviously 100vh? Is there a chance to implement an fall back to normal scroll for devices below some certain device-width or height in the script?

**Comment by Viewdesic** [comment]
If a content is langer than the container view, the content will be cutted off (horizontally) by default.
You must to scale this content on your own way depends on the view dimensions, using for example: `width` or `height` in percentage units. For particular devices you can turn-on normal scrolling using `$.fn.viewScroller.setUseScrollbar(false)` function but still the content must be responsive on view dimension.

**Comment by inseldesign** [comment]
Thanks this function i was looking for. 👍
