### ISSUE TITLE
How to get current index ?

### ISSUE THREAD

**Issue by rafipiccolo** [Viewdesic/viewScroller.js#3]
Hello,
I saw getCurrentViewIdx() on the documentation but it doesn't exist.
can you help me please ?

**Comment by Viewdesic** [comment]
Hi,
I removed this bug, so you can change the sub view using the code below:
(but before that, download the newest version of viewScroller)

```
var currentBagNbr = $.fn.viewScroller.getCurrentBagNbr();
$.fn.viewScroller.showSubView(currentBagIndex, 'next' / 'prev');
```

**Comment by rafipiccolo** [comment]
thx that will do the first step, but is there a way to get the current subview we are on when we do "up" or "down" ?

for exemple if i do "right", then "down", then "up", i'm not on the first subview
is it possible to force being on the first subview or is it at least possible to know which view subview we are on ?

**Comment by Viewdesic** [comment]
You can display specific view using this function:
   $.fn.viewScroller.showView(_your_unique_view_or_subview_id_);
for example:
   $.fn.viewScroller.showView('subview-c');

**Comment by fabioduque** [comment]
Hi @Viewdesic.
My question is the same as the original question, so I am not opening a new issue: How do I get the current view index?

I am not interested in showing a specific view index, like you answered to rafipiccolo. I want to know where I am, after the user scrolls around.

Maybe we could have something like:
1) $.fn.viewScroller.getView();
or
2) add a class `.is-active` to the `.mainview` we are on.

Is there any other way which I might be missing?

Thanks!

**Comment by onepartscissors** [comment]
Agree with @fabioduque above - getting the current "main view" index would be helpful for things like external navigations (or hiding the 'previous' button on page 1 and 'next' button on last page for example)

**Comment by jakubbyliniak** [comment]
In the meantime you can achieve it by defining your own function in viewScroller.js, This function should return object containing all bags informations. It can be like this:

   $.fn.viewScroller.lookInTheBag = function(){
       return allBagObjs;
    }

than you can use it in you own script. 

    myLookInTheBag = $.fn.viewScroller.lookInTheBag();

after that you can do bunch of stuff with it
for example get the number of all views in the .mainbag, knowing that the main bag is the first object:

    myLookInTheBag[0].viewsData.views.length

when you run this in afterChange or beforeChange callbacks you can also get the current postion each time you scroll the page:

    afterChange: function() { 
       myLookInTheBag = $.fn.viewScroller.lookInTheBag();
       console.log(myLookInTheBag[0].viewsData.activeView);
    }

You may need to play with the results a bit but this should not be too hard. Anyway, start with defining your own function, console.log what it returns and you will have better idea.
Good luck!
