### ISSUE TITLE
Stop the plugin when running an event.

### ISSUE THREAD

**Issue by MartDSam** [Viewdesic/viewScroller.js#4]
When I open a floater I want to stop the plugin. The reason is that the floater has scrolling and when I scroll the floater the site also keeps scrolling. Can you do that? Thank you. :) :)

**Comment by chem1st** [comment]
Hello! It's a late response, but maybe it will be useful.

In the `viewScroller.js` file you can find a piece of code doing this: `// Changes view depending on the mouse wheel direction`
Within this section, there is a part which prevents views from scrolling when ctrl key is pressed and when the time diff is less than 50 ms:
```
if (!event.ctrlKey && timeDiff > 50) {
    event.deltaY < 0 ? showMainView(direction.NEXT) : showMainView(direction.PREV);
}
```

You can add an additional condition here:
```
if (!event.ctrlKey && timeDiff > 50) {
    if (floater opened){
        event.deltaY < 0 ? showMainView(direction.NEXT) : showMainView(direction.PREV);
    }
}
```

**Comment by MartDSam** [comment]
Thank you @chem1st 

Really, it's been a long time. But thanks for your response.
